import 'package:flutter/material.dart';

/// Shared reader for static legal text (Privacy Policy, Terms of Service).
/// Content lives as a const string here rather than in a CMS/markdown file
/// since it changes rarely and shipping a new build already requires a
/// review pass for legal copy.
class LegalScreen extends StatelessWidget {
  final String title;
  final String body;

  const LegalScreen({super.key, required this.title, required this.body});

  static const String privacyPolicy = '''
Last updated: July 13, 2026

Luna Health ("we", "our", "the app") helps you track your menstrual cycle, symptoms, and wellness. This policy explains what data we collect, how it's used, and how it's protected.

1. DATA WE COLLECT
- Account info: email address and authentication details.
- Cycle data: period dates, symptoms, mood, and wellness check-ins you log.
- Usage data: app interactions needed to provide reminders and insights.
We do not collect location, contacts, or device data beyond what's required for notifications.

2. HOW WE USE YOUR DATA
- To generate cycle predictions, wellness insights, and reminders.
- To sync your data securely across your devices via Firebase.
- We do not sell your data, and we do not share your health data with advertisers.

3. DATA STORAGE & SECURITY
Your data is stored in Firebase (Google Cloud) with access restricted to your authenticated account. Data in transit is encrypted (HTTPS/TLS).

4. YOUR CONTROLS
- You can edit or delete any logged entry at any time.
- You can permanently delete your account and all associated data from Settings > Delete Account. This action is irreversible.

5. THIRD-PARTY SERVICES
We use Firebase (Authentication, Firestore, Cloud Messaging) to operate the app. These services process data on our behalf under their own security commitments.

6. CHANGES TO THIS POLICY
We may update this policy as the app evolves. Continued use after an update means you accept the revised policy.

7. CONTACT
Questions about this policy can be sent to the app's support contact listed on the app store page.
''';

  static const String termsOfService = '''
Last updated: July 13, 2026

By creating an account and using Luna Health, you agree to these terms.

1. WHAT LUNA HEALTH IS
Luna Health is a personal cycle and wellness tracking tool. Predictions and insights are estimates based on the data you provide and are not a substitute for professional medical advice, diagnosis, or treatment.

2. YOUR RESPONSIBILITIES
- Provide accurate information when logging cycle and symptom data for the best predictions.
- Keep your account credentials confidential; you're responsible for activity under your account.
- You must be able to legally consent to processing of your own health data to use this app.

3. MEDICAL DISCLAIMER
Luna Health does not provide medical advice. Always consult a qualified healthcare provider for medical concerns, including irregular cycles, severe symptoms, or fertility questions.

4. ACCOUNT & DATA
You may delete your account at any time from Settings, which permanently removes your data. We may suspend accounts used to abuse or disrupt the service.

5. LIMITATION OF LIABILITY
The app is provided "as is" without warranties of any kind. We are not liable for decisions made based on predictions or insights generated by the app.

6. CHANGES TO THESE TERMS
We may update these terms as the app evolves. Continued use after an update means you accept the revised terms.

7. CONTACT
Questions about these terms can be sent to the app's support contact listed on the app store page.
''';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF4F5FB),
      appBar: AppBar(
        backgroundColor: const Color(0xFFEEEDFE),
        elevation: 0,
        iconTheme: const IconThemeData(color: Color(0xFF3C3489)),
        title: Text(
          title,
          style: const TextStyle(
            color: Color(0xFF3C3489),
            fontWeight: FontWeight.w600,
          ),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Text(
            body.trim(),
            style: const TextStyle(
              fontSize: 13,
              height: 1.6,
              color: Color(0xFF2C2C2A),
            ),
          ),
        ),
      ),
    );
  }
}
